### ISSUE TITLE
#ASK BRO 

### ISSUE THREAD

**Issue by nikolaibarbravas** [marcussacana/DriveMirror#1]
File copied  5902
Copy log Paused due to Google quota limits - copy will resume in 1-2 minutes
Progress Working
06-22-20 2:28:37 PM

But today is 23 June bro.
This seems to stop, or hit by a limit I don't know. (edu)
Do I have to resume?
If you have to resume manually how to do it?
Im using RDP windows .

**Comment by nikolaibarbravas** [comment]
i open in https://script.google.com/home/executions

Copy Folder Extended | resume | Web App | Jun 23, 2020, 4:17:13 PM | 0.449 s | Failed
-- | -- | -- | -- | -- | --

**Comment by nikolaibarbravas** [comment]
Project | Function | Type | Start Time | Duration | Status
-- | -- | -- | -- | -- | --
Copy Folder Extended | resume | Web App | Jun 23, 2020, 4:17:13 PM | 0.449 s | Failed
Copy Folder Extended | getOAuthToken | Web App | Jun 23, 2020, 4:16:52 PM | 0.074 s | Completed
Copy Folder Extended | getOAuthToken | Web App | Jun 23, 2020, 4:16:52 PM | 0.048 s | Completed
Copy Folder Extended | getUserEmail | Web App | Jun 23, 2020, 4:16:51 PM | 0.046 s | Completed
Copy Folder Extended | doGet | Web App | Jun 23, 2020, 4:16:50 PM | 0.096 s | Completed
Copy Folder Extended | copy | Time-Driven | Jun 22, 2020, 9:30:33 PM | 22.006 s | Failed
Copy Folder Extended | copy | Time-Driven | Jun 22, 2020, 9:00:32 PM | 1686.933 s | Completed
Copy Folder Extended | copy | Time-Driven | Jun 22, 2020, 8:30:35 PM | 1684.208 s | Completed

**Comment by nikolaibarbravas** [comment]
Problem solved bro. i've been kicked by owner of that file . shit i being scammed .

**Comment by marcussacana** [comment]
also, i really did a the "copy folder extended", but this repo isn't for that, is a a new tool that aim to do the same thing of the "copy folder" but  with support for team drive/shared drives, then your issue shouldn't be fixed by reporting here.
By the way, I'm not complaining or anything, it doesn't bother me, just reporting that your issue would end up being wasted in this repository because it would never be answered.
